import pandas as pd
from datetime import date
from dateutil.relativedelta import relativedelta

def get_december_to_now_ranges():
    """
    Generated by AI Assistant
    Generates a list of (start_date, end_date) tuples for each month,
    starting from December 1st of the previous year up to the end of the previous month.
    """
    
    # 1. Define the End Boundary: Last day of the previous month
    # Since today is Nov 5, 2025, this sets the end date to Oct 31, 2025.
    end_date_period = date.today().replace(day=1) - relativedelta(days=1)
    
    # 2. Define the Start Boundary: December 1st of the previous year (2024)
    start_date_period = date.today().replace(month=12, day=1) - relativedelta(years=1)
    
    # --- Date Range Generation ---
    
    # Generate the start dates (Month Start frequency - 'MS')
    month_starts = pd.date_range(
        start=start_date_period,
        end=end_date_period, 
        freq='MS'
    )
    
    # Generate the end dates (Month End frequency - 'M')
    month_ends = pd.date_range(
        start=start_date_period,
        end=end_date_period, 
        freq='M'
    )
    
    # Combine and format the lists
    date_ranges = []
    # Note: We use the length of the shorter list just in case of edge issues
    for start, end in zip(month_starts, month_ends):
        date_ranges.append((
            start.strftime('%Y-%m-%d'), 
            end.strftime('%Y-%m-%d')
        ))
        
    return date_ranges